language: node_js
node_js:
  - "12"

branches:
  only:
    - master

before_install:
  - echo "Pre-Install Phase!"

install:
  - npm ci
  - npm install -g codecov

script:
  - npm run build
  - npm run test:cov
