# comment: no # do not comment PR with the result

coverage:
  #   range: 50..90 # coverage lower than 50 is red, higher than 90 green, between color code

  status:
    # do not run coverage on patch nor changes
    patch: no
    changes: no
